FROM python:3.10-slim-buster

# install git and libgl
RUN apt-get update -y
RUN apt-get install libgl1 git -y

# install & configure poetry
RUN python3 -m pip install poetry --no-cache-dir
RUN poetry config virtualenvs.in-project true

# make villager-bot dir
RUN mkdir villager-bot
WORKDIR /villager-bot

# install dependencies
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --no-dev --no-interaction

# copy common folder over
COPY common common
