from enum import IntEnum, auto


class PacketType(IntEnum):
    AUTH = auto()
    AUTH_RESPONSE = auto()
    DISCONNECT = auto()
    MISSING_PACKET = auto()
    CLUSTER_READY = auto()
    EVAL = auto()
    EVAL_RESPONSE = auto()
    EXEC = auto()
    EXEC_RESPONSE = auto()
    BROADCAST_REQUEST = auto()
    BROADCAST_RESPONSE = auto()
    COOLDOWN = auto()
    COOLDOWN_RESPONSE = auto()
    COOLDOWN_ADD = auto()
    COOLDOWN_RESET = auto()
    DM_MESSAGE = auto()
    DM_MESSAGE_REQUEST = auto()
    MINE_COMMAND = auto()
    MINE_COMMAND_RESPONSE = auto()
    MINE_COMMANDS_RESET = auto()
    CONCURRENCY_CHECK = auto()
    CONCURRENCY_CHECK_RESPONSE = auto()
    CONCURRENCY_ACQUIRE = auto()
    CONCURRENCY_RELEASE = auto()
    COMMAND_RAN = auto()
    ACQUIRE_PILLAGE_LOCK = auto()
    ACQUIRE_PILLAGE_LOCK_RESPONSE = auto()
    RELEASE_PILLAGE_LOCK = auto()
    PILLAGE = auto()
    REMINDER = auto()
    FETCH_STATS = auto()
    STATS_RESPONSE = auto()
    TRIVIA = auto()
    UPDATE_SUPPORT_SERVER_ROLES = auto()
    RELOAD_DATA = auto()
    ECON_PAUSE = auto()
    ECON_PAUSE_UNDO = auto()
    ECON_PAUSE_CHECK = auto()
    ACTIVE_FX_CHECK = auto()
    ACTIVE_FX_ADD = auto()
    ACTIVE_FX_REMOVE = auto()
    ACTIVE_FX_FETCH = auto()
